-- Seed menu data aligned with frontend mock items.
INSERT INTO menu_items (
    id,
    name_en,
    name_zh,
    description,
    calories,
    protein,
    carbs,
    fat,
    tags,
    allergens,
    hall_id,
    meal_slot,
    is_active
)
VALUES
    (
        'b1',
        'Quinoa Avocado Energy Bowl',
        '藜麦牛油果能量碗',
        '高纤维早餐碗，适合晨间补能。',
        420,
        15,
        45,
        22,
        ARRAY['vegan', 'high-protein', 'kosher'],
        ARRAY[]::text[],
        'hall1',
        'breakfast',
        TRUE
    ),
    (
        'b2',
        'Whole Wheat Chicken Sandwich',
        '全麦鸡胸肉三明治',
        '便捷高蛋白早餐，适合课间快速补给。',
        350,
        28,
        32,
        12,
        ARRAY['high-protein', 'low-calorie', 'halal'],
        ARRAY['gluten-free', 'dairy'],
        'hall2',
        'breakfast',
        TRUE
    ),
    (
        'b3',
        'Low-fat Milk Oatmeal',
        '低脂鲜奶燕麦粥',
        '低脂暖胃选项，适合清淡需求。',
        280,
        12,
        40,
        6,
        ARRAY['vegetarian', 'low-calorie'],
        ARRAY['dairy'],
        'hall1',
        'breakfast',
        TRUE
    ),
    (
        'l1',
        'Pan-seared Salmon with Veggies',
        '香煎三文鱼配时蔬',
        '优质蛋白和健康脂肪均衡搭配。',
        550,
        35,
        20,
        38,
        ARRAY['high-protein'],
        ARRAY['fish'],
        'hall1',
        'lunch',
        TRUE
    ),
    (
        'l2',
        'Korean Low-cal Konjac Noodles',
        '韩式低卡魔芋冷面',
        '低热量主食，适合控卡阶段。',
        210,
        8,
        42,
        2,
        ARRAY['vegan', 'spicy', 'low-calorie'],
        ARRAY['soy', 'sesame'],
        'hall2',
        'lunch',
        TRUE
    ),
    (
        'l3',
        'Sichuan Mapo Tofu Rice',
        '川香麻婆豆腐盖浇饭',
        '重口味高碳水，适合能量补充。',
        680,
        18,
        85,
        30,
        ARRAY['vegetarian', 'spicy'],
        ARRAY['soy', 'gluten-free'],
        'hall1',
        'lunch',
        TRUE
    ),
    (
        'd1',
        'Steamed Sea Bass',
        '清蒸海鲈鱼',
        '低油烹饪，蛋白密度高。',
        320,
        42,
        5,
        14,
        ARRAY['high-protein', 'low-calorie'],
        ARRAY['fish', 'soy'],
        'hall2',
        'dinner',
        TRUE
    ),
    (
        'd2',
        'Light Veggie Salad (Olive Oil)',
        '轻食时蔬沙拉 (配橄榄油)',
        '轻负担晚餐，油脂来源更优。',
        180,
        5,
        15,
        12,
        ARRAY['vegan', 'low-calorie'],
        ARRAY[]::text[],
        'hall1',
        'dinner',
        TRUE
    ),
    (
        'd3',
        'Deep Fried Calamari Rings',
        '炸鱿鱼圈',
        '口感酥脆，油脂和过敏风险较高。',
        450,
        15,
        40,
        25,
        ARRAY['shared-oil'],
        ARRAY['shellfish', 'gluten-free', 'egg'],
        'hall2',
        'dinner',
        TRUE
    )
ON CONFLICT (id) DO UPDATE
SET
    name_en = EXCLUDED.name_en,
    name_zh = EXCLUDED.name_zh,
    description = EXCLUDED.description,
    calories = EXCLUDED.calories,
    protein = EXCLUDED.protein,
    carbs = EXCLUDED.carbs,
    fat = EXCLUDED.fat,
    tags = EXCLUDED.tags,
    allergens = EXCLUDED.allergens,
    hall_id = EXCLUDED.hall_id,
    meal_slot = EXCLUDED.meal_slot,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();

-- Seed private RAG chunks. Embeddings are filled by API/script later.
INSERT INTO knowledge_chunks (source_type, source_id, content, metadata)
VALUES
    ('menu', 'b1', '藜麦牛油果能量碗富含膳食纤维和不饱和脂肪酸，适合早晨稳态供能。', '{"category":"dish","lang":"zh"}'::jsonb),
    ('menu', 'l1', '香煎三文鱼含优质蛋白和Omega-3脂肪酸，适合增肌及恢复。', '{"category":"dish","lang":"zh"}'::jsonb),
    ('menu', 'l2', '魔芋面热量低，饱腹感好，适合控制总能量摄入。', '{"category":"dish","lang":"zh"}'::jsonb),
    ('menu', 'd1', '清蒸海鲈鱼低油烹饪，蛋白质密度高且易消化。', '{"category":"dish","lang":"zh"}'::jsonb),
    ('menu', 'd3', '炸鱿鱼圈属于高油炸食品，并存在甲壳类过敏风险。', '{"category":"dish","lang":"zh"}'::jsonb),
    ('nutrition', 'n1', '增肌期建议每餐优先保证20到40克蛋白质，并分散摄入。', '{"category":"nutrition","lang":"zh"}'::jsonb),
    ('nutrition', 'n2', '减脂期更建议高蛋白和高纤维搭配，帮助维持饱腹感。', '{"category":"nutrition","lang":"zh"}'::jsonb),
    ('nutrition', 'n3', '对鱼类过敏用户应避免含fish标签菜品，必要时关注共用油锅提示。', '{"category":"nutrition","lang":"zh"}'::jsonb),
    ('nutrition', 'n4', '高强度训练日可提高午餐碳水比例，晚餐适度控制油脂。', '{"category":"nutrition","lang":"zh"}'::jsonb)
ON CONFLICT (source_type, source_id) DO UPDATE
SET
    content = EXCLUDED.content,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();
